[package]
name = "dlcl"
version = "0.1.0"
edition = "2021"
authors = ["Ole Weinert"]

[dependencies]
pyo3 = "0.19.2"
embedded-graphics-simulator = { version = "0.5.0", optional = true}
embedded-graphics = "0.8.1"

[lib]
name = "dlcl"
path = "src/lib.rs"